language: node_js
sudo: required
dist: trusty
node_js:
  - stable
  - 6
  - 4
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - uuid-dev
    - build-essential
    - qemu-utils
install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
  - sudo apt-get update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes  install virtualbox
  - npm install
  - wget https://github.com/rubiojr/vhd-util-convert/archive/master.tar.gz -O /tmp/vhd-util-convert.tar.gz
  - tar -xvf /tmp/vhd-util-convert.tar.gz
  - (cd vhd-util-convert-master && make)
  - df
  - pwd
  - echo "$TRAVIS_BUILD_DIR"
script:
  - npm test
  - find $TRAVIS_BUILD_DIR -name '*.vhd' -print0 | xargs -n 1 -0 ./vhd-util-convert-master/vhd-util scan -v
